version: 2

workflows:
  version: 2
  full_test:
    jobs:
      - npm_install
      - npm_test:
          requires:
            - npm_install

jobs:
  npm_install:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - run:
          name: Install deps via npm
          command: |
            npm ci
      - persist_to_workspace:
          root: .
          paths:
          - node_modules
  npm_test:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run npm test
          command: |
            npm run test:unit
