version: 2

workflows:
  version: 2
  build_and_release:
    jobs:
      - npm_install
      - unit_tests:
          requires:
            - npm_install
      - build_dist:
          requires:
            - npm_install
      - create_github_release:
          requires:
            - build_dist
          filters:
            branches:
              only:
                - scooby-doo
  release_process:
    jobs:
      - create_release_pull_request:
          filters:
            branches:
              only:
                - /^Version-v(\d+)[.](\d+)[.](\d+)/

jobs:
  npm_install:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - run:
          name: Install deps via npm
          command: |
            npm ci
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  unit_tests:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: |
            echo npm run test:unit
  build_dist:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build distributables
          command: |
            npm run dist
      - persist_to_workspace:
          root: .
          paths:
            - builds
            - dist
      - store_artifacts:
          path: builds
  create_github_release:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Create GitHub release
          command: |
            .circleci/scripts/release-create-gh-release
  create_release_pull_request:
    docker:
      - image: circleci/node:8.15.1-browsers
    steps:
      - checkout
      - run:
          name: Create GitHub Pull Request for version
          command: |
            .circleci/scripts/release-bump-manifest-version
            .circleci/scripts/release-create-release-pr
