#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if [[ "${CI:-}" != 'true' ]]
then
    printf '%s\n' 'CI environment variable must be set to true'
    exit 1
fi

if [[ "${CIRCLECI:-}" != 'true' ]]
then
    printf '%s\n' 'CIRCLECI environment variable must be set to true'
    exit 1
fi

printf '%s\n' 'Installing hub CLI'
pushd "$(mktemp -d)"
    curl -sSL 'https://github.com/github/hub/releases/download/v2.11.2/hub-linux-amd64-2.11.2.tgz' | tar xz
    PATH="$PATH:$PWD/hub-linux-amd64-2.11.2/bin"
popd

printf '%s\n' 'Creating "$VERSION" GitHub Release'

hub pull-request \
    --message "${CIRCLE_BRANCH/-/ } RC" --message ':package: :rocket:' \
    --base "$CIRCLE_PROJECT_USERNAME:$BASE_BRANCH" \
    --head "$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH"
