#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if [[ $CI != 'true' ]]
then
    printf '%s\n' 'CI environment variable must be set to true'
    exit 0
fi

if [[ $CIRCLECI != 'true' ]]
then
    printf '%s\n' 'CIRCLECI environment variable must be set to true'
    exit 0
fi

printf '%s\n' 'Bumping the manifest version'
